const Router = require('express')
const router = new Router()
const carServiceRouter = require('./carserviceRoutes')
const personalRouter = require('./personalRoutes')
const ordersRouter = require('./ordersRoutes')
const clientRouter = require('./clientRoutes')
const warehouseRouter = require('./warehouseRoutes')
const detailRouter = require('./detailRoutes')
const detailWarehouseRouter = require('./detailWarehouseRoutes')
const carRouter = require('./carRoutes')
const orderCarserviceRouter = require('./orderrCarservice')

router.use('/service', carServiceRouter)
router.use('/personal', personalRouter)
router.use('/orders', ordersRouter)
router.use('/client', clientRouter)
router.use('/warehouse', warehouseRouter)
router.use('/detail', detailRouter)
router.use('/detail-warehouse', detailWarehouseRouter)
router.use('/car', carRouter)
router.use('/order-carservice', orderCarserviceRouter)

module.exports = router